services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - back-end/.env
  node:
    container_name: node
    build: ./back-end
    ports:
      - 4000:4000
    env_file:
      - back-end/.env
    depends_on:
      - postgres
  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html
volumes:
  postgres-volume:
  react-volume:
