on:
    push:
      branches:
        - main
name: Build and Deploy on AWS
jobs:
    build:
      runs-on: self-hosted
      timeout-minutes: 10
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Create back-end env file
          uses: SpicyPizza/create-envfile@v1.3.1
          with:
            envkey_PORT: ${{secrets.PORT}}
            envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
            envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
            envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
            envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
            directory: back-end
            file_name: .env
            fail_on_empty: true
        - name: Create front-end env file
          uses: SpicyPizza/create-envfile@v1.3.1
          with:
            envkey_VITE_API_BASE_URL: ${{secrets.VITE_API_BASE_URL}}
            directory: front-end
            file_name: .env
            fail_on_empty: true
        - name: Run docker compose down
          run: docker compose down # Não apague os volumes, senão o banco de dados de produção vais er limpo.
        - name: Delete React docker volume
          run: if docker volume ls --quiet --filter name=FunForFamily_react-volume | grep -q .; then docker volume rm FunForFamily_react-volume; fi
        - name: Run docker compose up
          run: docker compose up --build -d